### ISSUE TITLE
All trains are being marked as departed

### ISSUE THREAD

**Issue by ondrej-mahdalik** [LinqToException/VirTracks#12] opened 2023-06-24 14:17 UTC
As you can see in the picture below, all trains are being incorrectly marked as departed.
![image](https://github.com/LinqToException/VirTracks/assets/49830945/a4b682fb-7654-476f-8078-850d35431c7f)

The issue first appeared this morning and seemed to have persisted since then, regardless of the server/station selected or browser used.

**Comment by LinqToException** [comment] 2023-06-24 14:19
I can confirm this issue is happening on multiple servers right now. It's probably the restart detection that has gone haywire. I'll ook into it.

**Comment by ondrej-mahdalik** [comment] 2023-06-24 14:58
Alright, thank you for the quick response!

**Comment by LinqToException** [comment] 2023-06-24 15:03
I've applied a super shoddy hotfix which only works when restarting the backend, then restarted the backend.

As far as I can tell, my old logic ("API hasn't said anything in the past minute") isn't working anymore, because the server seem to be either not gone, or not gone long enough. I think it's unlikely that most servers (not affected were de1, en1, en2, fr1, it1, pl1, pl2 to a lesser degree, pl4 to a lesser degree) were not restarted since then.

I'm afraid I'll have to re-think how I do data collection in VirTracks as a whole.

Thanks for the report (screenshot helped with the server code)! I'll try to figure something out and will follow up once I have something to present.

**Comment by LinqToException** [comment] 2023-06-24 18:42
I've pushed another fix, which is, again, just a hotfix.

VirTracks will now do some housekeeping and remove certain events (all events after >12h, highlighted events after arrival or 3h, whatever comes sooner). This also has the neat benefit of sending less data to clients, which eases the traffic requirements on server selection a bit.

This should prevent situations like today, however, it's not perfect. After a server restart, the trains are usually all over the place, and trains that did not run exactly on schedule (or even those that did) could now either skip stations (because the server placed them at the right spot post-restart), or arrive again at stations they already departed/arrived at (because they were running early before).

I'll keep this issue open, because ultimately, we'll need a proper way to determine whether a server was restarted or not. It would help an awful lot if SimRail's API could send some sort of "server start identifier" (e.g. "this is a random number I made up when I started", or "this is the unix epoch timestamp of when I started") in either /servers-open, /trains-open, /stations-open, or preferably all of them. I think the server id is not changing and therefore not usable, but I could be wrong. Any insight would be appreciated.

Otherwise, I suppose it could be an option to try to guess whether an update (old state -> current state) is deemed "impossible" (e.g. "more than X stations are suddenly occupied by someone else, and more than Y trains have changed position by more than Z meters") and then initiate the server restart procedure. This could be an option, albeit a slightly tricky one because figuring out whether a diff was improbably or not is going to take some... effort.

**Comment by ondrej-mahdalik** [comment] 2023-06-26 10:59
I did some research and can confirm that the server ID doesn't change after the server restart (or at least not after every restart).
Suggesting adding the server start timestamp on the official Discord server might be worth a try (there's a room dedicated to suggestions). However, the temporary fix seems to work fine for now.

**Comment by LinqToException** [comment] 2023-07-15 17:07
I'll close this issue for now as the problem has been resolved I think. Looking at [the forums](https://forum.simrail.eu/topic/6680-server-restart-times-changed/), and the data that I had, it seems like the servers had some hiccups. I'm led to believe that they didn't restart (or did so in a weird way?).

By now, it seems like all servers are normally rebooting again, which means that the cleanup should be done properly too. The hotfix ("delete data older than 12h") stays in place, just in case.

If this becomes a problem again in the future, we can re-open it.

**Closed by LinqToException** 2023-07-15 17:07 UTC
Labels: bug
